### ISSUE TITLE
Grafana compatibility issue

### ISSUE THREAD

**Issue by dmajere** [weaveworks/grafanalib#19]
Hi guys, your lib is awesome, and I want to help with its maintenance, so I've installed it from master branch, but It seems that master is not really working with the latest grafana (4.11, 4.12). 
What grafana version is library compatible with? Release 0.12 is working ok, but you've made lots of changes since then.

**Comment by jml** [comment]
@dmajere Thanks!

What specific incompatibilities do you see?

We're currently using grafanalib with grafana 4.1.2 and not seeing any problems.

**Comment by jml** [comment]
I stand corrected. We were seeing problems, which were introduced by #17 (c2b37e3561809c6ea3fad745b4f5645611b8ad0d) and fixed by #21 (611c664). Problem manifested as a parse error (red rectangle on top-right side) on the generated dashboard. These changes haven't been released yet, so you would have only seen the issue if you were running from master or another branch.

**Comment by dmajere** [comment]
Yes, I've been seeing this exact error. Can you please clarify, what branch I should use to fork from If I want to add something?

**Comment by jml** [comment]
Glad it's fixed!

Fork from `master` on this repo.
